--DROP TABLE IF EXISTS mpa, films, genres, genres_films, users, likes, friends;

CREATE TABLE IF NOT EXISTS mpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    release_date DATE,
    duration INTEGER NOT NULL,
    mpa_id INTEGER REFERENCES mpa,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genres_films (
    film_id BIGINT NOT NULL REFERENCES films,
    genre_id BIGINT NOT NULL REFERENCES genres,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR NOT NULL,
    login VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    birthday DATE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL REFERENCES films,
    user_id BIGINT NOT NULL REFERENCES users,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL REFERENCES users,
    friend_id BIGINT NOT NULL REFERENCES users,
    PRIMARY KEY (user_id, friend_id)
);